package combat_test

import (
	"math"
	"path/filepath"
	"testing"

	"github.com/go-theft-craft/minecraft-simulation/combat"
	"github.com/go-theft-craft/minecraft-simulation/geom"
	"github.com/go-theft-craft/minecraft-simulation/mctest"
)

// corpusDirectory holds one file per version, generated by internal/oracle
// from a prepared server jar and committed. The gate reads the committed
// numbers, so it runs without a jar, a workspace, or a JDK.
const corpusDirectory = "testdata/vanilla"

// corpusFiles names each version's corpus.
var corpusFiles = map[string]string{
	"1_8_9":  "1_8_9.json",
	"26_1_2": "26_1_2.json",
}

// loadCorpus reads one version's corpus and logs what it left out, so a green
// run says what it did not check.
func loadCorpus(t *testing.T, version string) mctest.CombatCorpus {
	t.Helper()

	corpus, err := mctest.LoadCombatCorpus(filepath.Join(corpusDirectory, corpusFiles[version]))
	if err != nil {
		t.Fatalf("load the %s corpus: %v", version, err)
	}
	for _, dropped := range corpus.Dropped {
		t.Log("not covered: " + dropped)
	}

	return corpus
}

// yawQuantisation bounds the one disagreement the strike comparison allows:
// the bonus knockback travels along the attacker's yaw through the game's
// 65536-entry sine table, while combat.Knockback pushes along the exact line
// between the two — directions that agree to about a quarter of a
// milliradian. Everything without a bonus is compared exactly.
const yawQuantisation = 2e-3

// widthDifference bounds the 26.1.2 base-impulse comparison: this version
// computes the same impulse at double width — Vec3.normalize's sqrt where
// 1.8.9 narrows through MathHelper.sqrt_double, a double 0.4 cap where 1.8.9
// caps at the widened float — and combat.Knockback carries 1.8.9's widths.
const widthDifference = 1e-7

// TestStrikesMatchVanilla replays the 1.8.9 corpus: full attack rounds, the
// damage compared exactly and the knockback exactly wherever no bonus rides
// the attacker's yaw.
func TestStrikesMatchVanilla(t *testing.T) {
	t.Parallel()

	corpus := loadCorpus(t, "1_8_9")
	if len(corpus.Strikes) == 0 {
		t.Fatal("the 1.8.9 corpus holds no strikes")
	}

	for _, c := range corpus.Strikes {
		t.Run(c.Name, func(t *testing.T) {
			t.Parallel()

			strike := combat.Strike{
				Base:           1, // the player's bare-handed attack-damage attribute
				Charge:         1, // this version has no cooldown
				Critical:       c.Critical,
				Sprinting:      c.Sprint,
				KnockbackLevel: c.Knockback,
			}

			wantDamage, err := c.DamageValue()
			if err != nil {
				t.Fatal(err)
			}
			if got := combat.Damage(strike); got != wantDamage {
				t.Errorf("Damage = %v, the jar dealt %v", got, wantDamage)
			}

			dx, err := mctest.ParseDouble(c.DX)
			if err != nil {
				t.Fatal(err)
			}
			dz, err := mctest.ParseDouble(c.DZ)
			if err != nil {
				t.Fatal(err)
			}
			motion, err := mctest.ParseDoubles(c.Motion)
			if err != nil {
				t.Fatal(err)
			}
			want, err := mctest.ParseDoubles(c.Result)
			if err != nil {
				t.Fatal(err)
			}

			from := geom.Vec3{X: 0.5, Y: 64, Z: 0.5}
			to := geom.Vec3{X: 0.5 + dx, Y: 64, Z: 0.5 + dz}
			got := combat.Knockback(from, to, strike,
				geom.Vec3{X: motion[0], Y: motion[1], Z: motion[2]})

			tolerance := 0.0
			if c.Knockback > 0 || c.Sprint {
				tolerance = yawQuantisation
			}
			compareMotion(t, got, want, tolerance)
		})
	}
}

// TestChargesMatchVanilla replays the 26.1.2 cooldown curve, exactly: the
// curve is float32 arithmetic on both sides, and a tolerance here would hide
// the middle being wrong, which is where the damage composition reads it.
func TestChargesMatchVanilla(t *testing.T) {
	t.Parallel()

	corpus := loadCorpus(t, "26_1_2")
	if len(corpus.Charges) == 0 {
		t.Fatal("the 26.1.2 corpus holds no cooldown curve")
	}

	cooldown := profileFor(t, "26_1_2").Cooldown()
	speed := profileFor(t, "26_1_2").AttackSpeed()
	for _, c := range corpus.Charges {
		want, err := c.ChargeValue()
		if err != nil {
			t.Fatal(err)
		}
		if got := cooldown.Charge(c.Ticks, speed); got != want {
			t.Errorf("Charge(%d) = %v, the jar says %v", c.Ticks, got, want)
		}
	}
}

// TestBaseImpulsesMatchVanilla replays the 26.1.2 base knockback: the same
// impulse as 1.8.9's, computed by its jar at double width, compared within
// the width difference.
func TestBaseImpulsesMatchVanilla(t *testing.T) {
	t.Parallel()

	corpus := loadCorpus(t, "26_1_2")
	if len(corpus.Impulses) == 0 {
		t.Fatal("the 26.1.2 corpus holds no impulses")
	}

	for _, c := range corpus.Impulses {
		t.Run(c.Name, func(t *testing.T) {
			t.Parallel()

			dx, err := mctest.ParseDouble(c.DX)
			if err != nil {
				t.Fatal(err)
			}
			dz, err := mctest.ParseDouble(c.DZ)
			if err != nil {
				t.Fatal(err)
			}
			motion, err := mctest.ParseDoubles(c.Motion)
			if err != nil {
				t.Fatal(err)
			}
			want, err := mctest.ParseDoubles(c.Result)
			if err != nil {
				t.Fatal(err)
			}

			// hurtServer's dx and dz point from the target toward the
			// attacker, so the attacker stands at the offset and the target
			// at the origin.
			from := geom.Vec3{X: dx, Z: dz}
			got := combat.Knockback(from, geom.Vec3{}, combat.Strike{Charge: 1},
				geom.Vec3{X: motion[0], Y: motion[1], Z: motion[2]})

			compareMotion(t, got, want, widthDifference)
		})
	}
}

// TestBothVersionsHaveACombatCorpus refuses a one-version gate, and is where
// the cooldown's absence is asserted as recorded rather than skipped.
//
// There is no conform.Scenario to register from here — the simulation cannot
// import the examples module that harness lives in — so the two-version rule
// is a test, the same shape mining's corpus carries. The 47 lane's smaller
// claims are stated where they are smaller: protocol 47 names no attacker, so
// nothing here or in the corpus attributes a hit, and the 26.1.2 lane's
// composition is transcribed rather than executed, which its corpus's Dropped
// list says in as many words.
func TestBothVersionsHaveACombatCorpus(t *testing.T) {
	t.Parallel()

	for _, version := range versions {
		corpus := loadCorpus(t, version)
		fighter := profileFor(t, version)

		if present := fighter.Cooldown().Present(); present == (corpus.CooldownAbsent != "") {
			t.Errorf("%s: the profile says cooldown present=%v and the corpus says absent=%q",
				version, present, corpus.CooldownAbsent)
		}
		if corpus.CooldownAbsent == "" && len(corpus.Charges) == 0 {
			t.Errorf("%s: neither a cooldown curve nor a recorded reason for having none",
				version)
		}
	}
}

// compareMotion checks one knockback vector against the jar's, exactly when
// the tolerance is zero.
func compareMotion(t *testing.T, got geom.Vec3, want [3]float64, tolerance float64) {
	t.Helper()

	for at, pair := range [][2]float64{
		{got.X, want[0]}, {got.Y, want[1]}, {got.Z, want[2]},
	} {
		axis := [3]string{"X", "Y", "Z"}[at]
		if tolerance == 0 {
			if pair[0] != pair[1] {
				t.Errorf("motion %s = %v, the jar left %v", axis, pair[0], pair[1])
			}

			continue
		}
		if math.Abs(pair[0]-pair[1]) > tolerance {
			t.Errorf("motion %s = %v, the jar left %v (beyond %v)",
				axis, pair[0], pair[1], tolerance)
		}
	}
}
