package mctest

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"strconv"
)

// MiningCorpus is what one version's game says about breaking blocks.
//
// It is not a Captured and it is not a Fixture. A Fixture holds a trajectory the
// game computed tick by tick; a Captured holds checkpoints a server chose to
// send. This holds one answer per question, because a break time is not a
// trajectory: it is a pure function of a block, a tool, an enchantment, two
// effects, and where the player is standing, and the game answers it in one
// call.
//
// Every number in it is the jar's. The corpus is generated by internal/oracle
// from a prepared server jar and is committed, so the gate that reads it runs
// without a workspace while the numbers stay traceable to the version that
// stated them.
type MiningCorpus struct {
	// Version is the game the answers came from, as the directory
	// minecraft-reference prepared it under: "1.8.9" or "26.1.2".
	Version string `json:"version"`
	// Source says where the numbers came from — the harness, the jar, and the
	// date. A number nobody can trace back to a run is a claim rather than
	// evidence.
	Source string `json:"source"`
	// Dropped says which parts of the cross product this corpus does not hold,
	// and why. Four axes multiply to thousands of cases; sampling is correct
	// and sampling silently is not, so a reader of the gate is told what was
	// left out rather than being left to infer that everything is covered.
	Dropped []string `json:"dropped"`
	// Cases are the questions and the game's answers, in the order the
	// generator asked them.
	Cases []MiningCase `json:"cases"`
}

// MiningCase is one question and the game's answer to it.
//
// The three floats cross as hexadecimal literals because they are float32
// values the game computed and a decimal rendering of one is a rounding of it.
// Go's strconv reads the format Java's Float.toHexString writes.
type MiningCase struct {
	// Name labels the case for a failure message.
	Name string `json:"name"`
	// Block and Held are registry names in this version's own vocabulary. The
	// two versions do not agree on them — 1.8.9's cobweb is "web" and 26.1's is
	// "cobweb" — which is why a corpus is per version rather than shared.
	Block string `json:"block"`
	// Held is empty for a bare hand.
	Held string `json:"held,omitempty"`
	// Efficiency is the enchantment level on the held item, zero for none.
	Efficiency int `json:"efficiency,omitempty"`
	// Haste and MiningFatigue are amplifiers, present only when their flag is
	// set: amplifier zero is haste I rather than no haste.
	Haste         int  `json:"haste,omitempty"`
	MiningFatigue int  `json:"miningFatigue,omitempty"`
	HasHaste      bool `json:"hasHaste,omitempty"`
	HasFatigue    bool `json:"hasFatigue,omitempty"`
	// Underwater is the player's eye in water; Airborne is the player off the
	// ground.
	Underwater bool `json:"underwater,omitempty"`
	Airborne   bool `json:"airborne,omitempty"`

	// Hardness is what the jar says the block's hardness is. A version may say
	// -1 for a block whose generated data says nothing at all, which is why
	// this is recorded rather than assumed to match the dataset.
	Hardness string `json:"hardness"`
	// Speed is the held item's multiplier against this block, as the jar
	// computes it: InventoryPlayer.getStrVsBlock on 1.8.9 and
	// ItemStack.getDestroySpeed on 26.1.2.
	Speed string `json:"speed"`
	// Harvestable is whether the held item is good enough to drop the block.
	Harvestable bool `json:"harvestable"`
	// Damage is the per-tick progress fraction the jar computed.
	Damage string `json:"damage"`
	// Ticks is how many times the game adds Damage before its running float32
	// reaches one, or -1 when it never does — which covers both a block with no
	// hardness and a fraction too small for the game's own accumulator.
	Ticks int `json:"ticks"`
	// Divergence, when set, says this version's generated data is known to
	// disagree with the jar for this case, and why. The gate asserts the
	// disagreement rather than skipping it, so the day the data is corrected
	// the case fails and the marker comes off.
	Divergence string `json:"divergence,omitempty"`
}

// HardnessValue reads the hardness the jar reported.
func (c MiningCase) HardnessValue() (float64, error) { return parseFloat32(c.Hardness) }

// SpeedValue reads the tool speed the jar reported.
func (c MiningCase) SpeedValue() (float64, error) { return parseFloat32(c.Speed) }

// DamageValue reads the per-tick fraction the jar reported.
func (c MiningCase) DamageValue() (float64, error) { return parseFloat32(c.Damage) }

// parseFloat32 reads one of the harness's hexadecimal floats.
//
// At single width, then widened, because that is what the number is: a float32
// the game computed. Parsing it at double width would accept a literal no
// float32 holds and hide the difference behind a comparison that then passes.
func parseFloat32(text string) (float64, error) {
	value, err := strconv.ParseFloat(text, 32)
	if err != nil {
		return 0, fmt.Errorf("mctest: read %q: %w", text, err)
	}

	return value, nil
}

// Save writes a corpus where a gate will look for it.
func (c MiningCorpus) Save(path string) error {
	content, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return fmt.Errorf("mctest: encode corpus: %w", err)
	}

	if err := os.WriteFile(path, append(content, '\n'), 0o644); err != nil {
		return fmt.Errorf("mctest: write corpus: %w", err)
	}

	return nil
}

// LoadMiningCorpus reads one version's corpus.
//
// A corpus with no cases is refused rather than returned. A matrix gate with no
// cases passes and proves nothing, and the emptiness would be discovered as a
// green run rather than as a failure.
func LoadMiningCorpus(path string) (MiningCorpus, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return MiningCorpus{}, fmt.Errorf("mctest: read corpus: %w", err)
	}

	var corpus MiningCorpus
	decoder := json.NewDecoder(bytes.NewReader(content))
	// An unknown field is a corpus written against a different format, and
	// reading it would silently ignore whatever it was trying to say.
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&corpus); err != nil {
		return MiningCorpus{}, fmt.Errorf("%w %s: %w", ErrFixture, path, err)
	}

	switch {
	case len(corpus.Cases) == 0:
		return MiningCorpus{}, fmt.Errorf(
			"%w %s: it holds no cases, and a matrix gate with none passes and proves nothing",
			ErrFixture, path,
		)
	case corpus.Source == "":
		return MiningCorpus{}, fmt.Errorf(
			"%w %s: its numbers name no run to trace them to", ErrFixture, path,
		)
	case len(corpus.Dropped) == 0:
		return MiningCorpus{}, fmt.Errorf(
			"%w %s: it says nothing about what it dropped from the cross product",
			ErrFixture, path,
		)
	}

	return corpus, nil
}
