package placement_test

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-theft-craft/minecraft-protocol/data"
	gen "github.com/go-theft-craft/minecraft-protocol/generated/java/v1_8"
	gen26 "github.com/go-theft-craft/minecraft-protocol/generated/java/v26_1"

	"github.com/go-theft-craft/minecraft-simulation/geom"
	"github.com/go-theft-craft/minecraft-simulation/mctest"
	"github.com/go-theft-craft/minecraft-simulation/mining"
	"github.com/go-theft-craft/minecraft-simulation/placement"
	"github.com/go-theft-craft/minecraft-simulation/profile/java/v1_8"
	"github.com/go-theft-craft/minecraft-simulation/profile/java/v26_1"
	"github.com/go-theft-craft/minecraft-simulation/sim"
	"github.com/go-theft-craft/minecraft-simulation/world"
)

// corpusDirectory holds one file per version, generated by internal/oracle from
// a prepared server jar and committed. The gate reads the committed numbers, so
// it runs without a jar, a workspace, or a JDK.
const corpusDirectory = "testdata/vanilla"

// versions are the two lanes, and there are two of them on purpose. A stage
// that gates one version and skips the other is the failure this milestone was
// subdivided to prevent.
var versions = []string{"1_8_9", "26_1_2"}

// TestPlacedStatesMatchVanilla is the gate.
//
// The comparison is on the handle, which means it is on the version's own state
// number: a placement that produced the right block in the wrong orientation
// resolves a different handle, and a client sent that handle draws a different
// block from the one the server has.
func TestPlacedStatesMatchVanilla(t *testing.T) {
	t.Parallel()

	for _, version := range versions {
		corpus := loadCorpus(t, version)

		t.Run(version, func(t *testing.T) {
			t.Parallel()

			// What this corpus covers and what it does not, said where a reader
			// of a green run sees it. A placement rule answers something for
			// every block, and only these families are checked.
			for _, covered := range corpus.Covers {
				t.Log("covers: " + covered)
			}
			for _, dropped := range corpus.Dropped {
				t.Log("not covered: " + dropped)
			}

			profile := profileFor(t, version)
			placer := placerFor(t, profile)
			items := itemsFor(t, version)

			for _, c := range corpus.Cases {
				t.Run(c.Name, func(t *testing.T) {
					t.Parallel()

					want := stateHandle(t, version, profile, c)
					got, err := placer.PlacedState(
						itemOf(t, items, c.Item),
						placement.Target{
							Clicked: geom.BlockPos{X: c.Clicked[0], Y: c.Clicked[1], Z: c.Clicked[2]},
							Placed:  geom.BlockPos{X: c.Clicked[0], Y: c.Clicked[1] + 1, Z: c.Clicked[2]},
						},
						mining.Face(c.Face),
						c.Yaw,
						geom.Vec3{X: c.Cursor[0], Y: c.Cursor[1], Z: c.Cursor[2]},
					)
					if err != nil {
						t.Fatalf("PlacedState: %v; the game places %s state %d",
							err, c.Block, c.State)
					}
					if got != want {
						t.Fatalf("placed handle %d, want %d — the game places %s state %d",
							got, want, c.Block, c.State)
					}
				})
			}
		})
	}
}

// TestBothVersionsHaveAPlacementCorpus refuses a one-version gate.
//
// The simulation cannot import relay's examples module to register a
// conform.Scenario, so the two-version rule is a test. mctest carries the same
// one for captured trajectories and mining carries it for break times; this is
// its counterpart for placement.
func TestBothVersionsHaveAPlacementCorpus(t *testing.T) {
	t.Parallel()

	for _, version := range versions {
		if corpus := loadCorpus(t, version); len(corpus.Cases) == 0 {
			t.Fatalf("%s has no placement corpus", version)
		}
	}
}

// TestTheTwoCorporaAskTheSameQuestions keeps the two lanes comparable.
//
// The items are named differently in the two versions and the questions are
// not: a case on one side and not the other is a lane that drifted, and the
// drift would show up as one version quietly covering less.
func TestTheTwoCorporaAskTheSameQuestions(t *testing.T) {
	t.Parallel()

	first := loadCorpus(t, versions[0])
	second := loadCorpus(t, versions[1])

	if len(first.Cases) != len(second.Cases) {
		t.Fatalf("%s asks %d questions and %s asks %d",
			versions[0], len(first.Cases), versions[1], len(second.Cases))
	}
	for at, c := range first.Cases {
		other := second.Cases[at]
		if other.Name != c.Name {
			t.Errorf("question %d is %q on %s and %q on %s",
				at, c.Name, versions[0], other.Name, versions[1])
		}
		if other.Face != c.Face || other.Cursor != c.Cursor || other.Yaw != c.Yaw {
			t.Errorf("%s is asked differently on the two versions: "+
				"face %d/%d, cursor %v/%v, yaw %v/%v",
				c.Name, c.Face, other.Face, c.Cursor, other.Cursor, c.Yaw, other.Yaw)
		}
	}
}

// stateHandle turns the state the jar named into the handle this version mints
// for it.
//
// The two versions name a state differently — four bits of metadata against a
// flat id — so this is where the corpus's one integer becomes version-specific,
// and it is the only place in the gate that knows which version it is looking
// at.
func stateHandle(
	t *testing.T, version string, profile sim.Profile, c mctest.PlacementCase,
) world.BlockRef {
	t.Helper()

	switch version {
	case "1_8_9":
		ref, ok := v1_8.RefState(profile, unqualified(c.Block), c.State)
		if !ok {
			t.Fatalf("this version has no state %d of %q", c.State, c.Block)
		}

		return ref
	case "26_1_2":
		ref, ok := v26_1.RefState(profile, data.BlockStateID(c.State))
		if !ok {
			t.Fatalf("this version has no state %d", c.State)
		}

		return ref
	default:
		t.Fatalf("no state numbering for %q", version)

		return 0
	}
}

// loadCorpus reads one version's committed corpus.
func loadCorpus(t *testing.T, version string) mctest.PlacementCorpus {
	t.Helper()

	corpus, err := mctest.LoadPlacementCorpus(filepath.Join(corpusDirectory, version+".json"))
	if err != nil {
		t.Fatalf("%s: %v", version, err)
	}

	return corpus
}

// profileFor builds the profile whose rules the corpus was recorded against.
func profileFor(t *testing.T, version string) sim.Profile {
	t.Helper()

	set := dataFor(t, version)

	var (
		built sim.Profile
		err   error
	)
	switch version {
	case "1_8_9":
		built, err = v1_8.New(set)
	case "26_1_2":
		built, err = v26_1.New(set)
	default:
		t.Fatalf("no profile for %q", version)
	}
	if err != nil {
		t.Fatalf("%s: build the profile: %v", version, err)
	}

	return built
}

// dataFor loads one version's game data.
func dataFor(t *testing.T, version string) *data.Set {
	t.Helper()

	var (
		set *data.Set
		err error
	)
	switch version {
	case "1_8_9":
		set, err = gen.Data()
	case "26_1_2":
		set, err = gen26.Data()
	default:
		t.Fatalf("no data set for %q", version)
	}
	if err != nil {
		t.Fatalf("%s: load the data set: %v", version, err)
	}

	return set
}

// itemsFor returns the item registry the corpus's item names resolve against.
func itemsFor(t *testing.T, version string) data.ItemRegistry {
	t.Helper()

	return dataFor(t, version).Items()
}

// placerFor asserts the optional interface rather than assuming it. New returns
// a sim.Profile, and a seam nobody asserts is the defect the master plan records
// against M7.
func placerFor(t *testing.T, built sim.Profile) placement.Placer {
	t.Helper()

	placer, ok := built.(placement.Placer)
	if !ok {
		t.Fatalf("%T cannot place", built)
	}

	return placer
}

// itemOf resolves an item the corpus names.
func itemOf(t *testing.T, items data.ItemRegistry, name string) data.ItemID {
	t.Helper()

	item, ok := items.ByName(unqualified(name))
	if !ok {
		t.Fatalf("this version has no item %q", name)
	}

	return item.ID
}

// unqualified drops the namespace from a registry name. The corpus holds the
// name the jar used, namespace and all, because that is what the game called
// it; the generated data is keyed by the path alone.
func unqualified(name string) string {
	if _, path, found := strings.Cut(name, ":"); found {
		return path
	}

	return name
}
