// Package mining_test holds the gate: what this package computes against what
// the two games compute.
//
// It is an external test package because the profiles it needs import mining,
// and a test inside the package naming them would be an import cycle.
package mining_test

import (
	"errors"
	"math"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-theft-craft/minecraft-protocol/data"
	gen "github.com/go-theft-craft/minecraft-protocol/generated/java/v1_8"
	gen26 "github.com/go-theft-craft/minecraft-protocol/generated/java/v26_1"

	"github.com/go-theft-craft/minecraft-simulation/mctest"
	"github.com/go-theft-craft/minecraft-simulation/mining"
	"github.com/go-theft-craft/minecraft-simulation/profile/java/v1_8"
	"github.com/go-theft-craft/minecraft-simulation/profile/java/v26_1"
	"github.com/go-theft-craft/minecraft-simulation/sim"
	"github.com/go-theft-craft/minecraft-simulation/world"
)

// corpusDirectory holds one file per version, generated by internal/oracle from
// a prepared server jar and committed. The gate reads the committed numbers, so
// it runs without a jar, a workspace, or a JDK.
const corpusDirectory = "testdata/vanilla"

// versions are the two lanes, and there are two of them on purpose. A stage
// that gates one version and skips the other is the failure this milestone was
// subdivided to prevent.
var versions = []string{"1_8_9", "26_1_2"}

// TestBreakTimesMatchVanilla is the matrix gate.
//
// The comparison is exact. A break time is an integer number of ticks and the
// game computes it deterministically; a tolerance here would hide the
// off-by-one an anti-cheat will not.
func TestBreakTimesMatchVanilla(t *testing.T) {
	t.Parallel()

	for _, version := range versions {
		corpus := loadCorpus(t, version)

		t.Run(version, func(t *testing.T) {
			t.Parallel()

			// What the sample left out, said where a reader of a green run
			// sees it. A matrix that silently samples reads as "covered
			// everything" when it did not.
			for _, dropped := range corpus.Dropped {
				t.Log("not covered: " + dropped)
			}

			profile := profileFor(t, version)
			classifier := classifierFor(t, profile)
			names := namesFor(t, profile)
			items := itemsFor(t, version)

			for _, c := range corpus.Cases {
				t.Run(c.Name, func(t *testing.T) {
					t.Parallel()

					checkCase(t, checkable{
						profile:    classifier,
						names:      names,
						items:      items,
						corpusCase: c,
					})
				})
			}
		})
	}
}

// TestBothVersionsHaveABreakTimeCorpus refuses a one-version gate.
//
// There is no conform.Scenario to register from here — the simulation cannot
// import the examples module that harness lives in — so the two-version rule is
// a test. mctest carries the same one for captured trajectories; this is its
// counterpart for break times.
func TestBothVersionsHaveABreakTimeCorpus(t *testing.T) {
	t.Parallel()

	for _, version := range versions {
		if corpus := loadCorpus(t, version); len(corpus.Cases) == 0 {
			t.Fatalf("%s has no break-time corpus", version)
		}
	}
}

// TestTheTwoCorporaAskTheSameQuestions is what keeps the two lanes comparable.
//
// The blocks are named differently in the two versions and the questions are
// not: a case that exists on one side and not the other is a lane that drifted,
// and the drift would show up as one version quietly covering less.
func TestTheTwoCorporaAskTheSameQuestions(t *testing.T) {
	t.Parallel()

	first := loadCorpus(t, versions[0])
	second := loadCorpus(t, versions[1])

	if len(first.Cases) != len(second.Cases) {
		t.Fatalf("%s asks %d questions and %s asks %d",
			versions[0], len(first.Cases), versions[1], len(second.Cases))
	}
	for at, c := range first.Cases {
		if other := second.Cases[at].Name; other != c.Name {
			t.Errorf("question %d is %q on %s and %q on %s",
				at, c.Name, versions[0], other, versions[1])
		}
	}
}

// checkable is one case and everything the version brings to it.
type checkable struct {
	profile    mining.Classifier
	names      sim.BlockNames
	items      data.ItemRegistry
	corpusCase mctest.MiningCase
}

// checkCase compares this module's answer against the game's.
//
// A case marked as a known divergence is checked the other way round: it must
// still disagree, and by the amount the marker describes. Asserting the
// disagreement rather than skipping the case is what makes the correction
// visible — the day the generated data is fixed, this fails and the marker
// comes off.
func checkCase(t *testing.T, check checkable) {
	t.Helper()

	c := check.corpusCase
	ref := refOf(t, check.names, c.Block)

	held := mining.Held{Efficiency: c.Efficiency}
	if c.Held != "" {
		held.Item = itemOf(t, check.items, c.Held)
	}

	conditions, err := check.profile.Conditions(ref, held, mining.Effects{
		Haste:         c.Haste,
		MiningFatigue: c.MiningFatigue,
		HasHaste:      c.HasHaste,
		HasFatigue:    c.HasFatigue,
	}, c.Underwater, c.Airborne)
	if err != nil {
		t.Fatalf("Conditions: %v", err)
	}

	hardness := check.profile.Hardness(ref)
	ticks, ticksErr := mining.BreakTicks(hardness, conditions)
	damage, damageErr := mining.Damage(hardness, conditions)

	if c.Divergence != "" {
		if agrees(t, c, conditions, damage, damageErr, ticks, ticksErr) {
			t.Fatalf("this case is marked as a known divergence and no longer diverges:\n%s\n"+
				"remove the marker in internal/oracle/mining_test.go and regenerate",
				c.Divergence)
		}
		t.Skipf("known divergence: %s", c.Divergence)
	}

	checkHardness(t, hardness, valueOf(t, c.HardnessValue))

	// An unbreakable block is an outcome, not a very long time. The game
	// answers it as a progress of zero; this package answers it as an error,
	// and the two are the same statement.
	//
	// Neither the tool speed nor the harvest legality is compared for one.
	// Both games return before consulting either — 1.8.9's
	// getPlayerRelativeBlockHardness on a hardness below zero, 26.1.2's
	// getDestroyProgress on a destroy speed of -1 — so what a version says
	// about a tool against bedrock is unobservable, and a comparison of it
	// would be a comparison of two dead ends.
	if c.Ticks == -1 {
		if valueOf(t, c.DamageValue) == 0 {
			if !errors.Is(ticksErr, mining.ErrUnbreakable) {
				t.Fatalf("BreakTicks = %d, %v; the game breaks nothing here", ticks, ticksErr)
			}

			return
		}
		if !errors.Is(ticksErr, mining.ErrNeverBreaks) {
			t.Fatalf("BreakTicks = %d, %v; the game's own accumulator never finishes this",
				ticks, ticksErr)
		}

		return
	}

	// The classification, because it is the half the two versions do
	// differently and the half a wrong answer usually comes from. A speed that
	// is already wrong makes every number after it wrong for a reason the
	// failure would not name.
	if want := valueOf(t, c.SpeedValue); !identical(conditions.Speed, want) {
		t.Errorf("tool speed %v, the game says %v", conditions.Speed, want)
	}
	if conditions.Harvestable != c.Harvestable {
		t.Errorf("harvestable %t, the game says %t", conditions.Harvestable, c.Harvestable)
	}

	if damageErr != nil {
		t.Fatalf("Damage: %v; the game says %v", damageErr, valueOf(t, c.DamageValue))
	}
	if want := valueOf(t, c.DamageValue); !identical(damage, want) {
		t.Errorf("per-tick damage %v, the game computes %v", damage, want)
	}
	if ticksErr != nil {
		t.Fatalf("BreakTicks: %v; the game takes %d ticks", ticksErr, c.Ticks)
	}
	if ticks != c.Ticks {
		t.Errorf("computed %d ticks, vanilla takes %d", ticks, c.Ticks)
	}
}

// agrees reports whether a divergent case has stopped diverging.
func agrees(
	t *testing.T, c mctest.MiningCase, conditions mining.Conditions,
	damage float64, damageErr error, ticks int, ticksErr error,
) bool {
	t.Helper()

	if !identical(conditions.Speed, valueOf(t, c.SpeedValue)) || conditions.Harvestable != c.Harvestable {
		return false
	}
	if c.Ticks == -1 {
		return ticksErr != nil
	}

	return damageErr == nil && ticksErr == nil &&
		identical(damage, valueOf(t, c.DamageValue)) && ticks == c.Ticks
}

// checkHardness compares the generated hardness against the jar's.
//
// A version may state a hardness the generated data leaves out. 1.8.9's bedrock
// is -1 in the jar and absent in the data; 26.1.2's is -1 in both. Either way
// the block is unbreakable, and the outcome is checked above — what is checked
// here is that a breakable block's hardness is the number the game holds, which
// is where a corrected dataset would show up first.
//
// At single width, because that is the width the number has in the game. The
// dataset states a hardness as a decimal — leaves are 0.2 — and the jar holds
// the float32 nearest it, 0.20000000298023224. Comparing the two at double
// width fails on every block whose hardness is not a dyadic fraction, and
// nothing is wrong with any of them: the arithmetic that uses the hardness
// narrows it first, which is why every damage in this corpus matches while
// three hardnesses did not.
func checkHardness(t *testing.T, generated *float64, stated float64) {
	t.Helper()

	if stated < 0 {
		if generated != nil && *generated >= 0 {
			t.Errorf("the data gives this block a hardness of %v; the game says %v, "+
				"which is how it says the block cannot be broken", *generated, stated)
		}

		return
	}
	if generated == nil {
		t.Errorf("the data gives this block no hardness; the game says %v", stated)

		return
	}
	if float32(*generated) != float32(stated) {
		t.Errorf("hardness %v, the game says %v", *generated, stated)
	}
}

// identical compares two values by their bits, so that a one-ulp drift is a
// failure rather than a rounding detail. Both sides are float32 values the game
// computed, widened; two that differ at all differ because an arithmetic step
// differs.
func identical(a, b float64) bool {
	return math.Float64bits(a) == math.Float64bits(b)
}

// valueOf reads one of the corpus's hexadecimal floats.
func valueOf(t *testing.T, read func() (float64, error)) float64 {
	t.Helper()

	value, err := read()
	if err != nil {
		t.Fatalf("read the corpus: %v", err)
	}

	return value
}

// loadCorpus reads one version's committed corpus.
func loadCorpus(t *testing.T, version string) mctest.MiningCorpus {
	t.Helper()

	corpus, err := mctest.LoadMiningCorpus(filepath.Join(corpusDirectory, version+".json"))
	if err != nil {
		t.Fatalf("%s: %v", version, err)
	}

	return corpus
}

// profileFor builds the profile whose rules the corpus was recorded against.
func profileFor(t *testing.T, version string) sim.Profile {
	t.Helper()

	var (
		set   *data.Set
		err   error
		build func(*data.Set) (sim.Profile, error)
	)
	switch version {
	case "1_8_9":
		set, err = gen.Data()
		build = v1_8.New
	case "26_1_2":
		set, err = gen26.Data()
		build = v26_1.New
	default:
		t.Fatalf("no profile for %q", version)
	}
	if err != nil {
		t.Fatalf("%s: load the data set: %v", version, err)
	}

	built, err := build(set)
	if err != nil {
		t.Fatalf("%s: build the profile: %v", version, err)
	}

	return built
}

// itemsFor returns the item registry the corpus's tool names resolve against.
func itemsFor(t *testing.T, version string) data.ItemRegistry {
	t.Helper()

	var (
		set *data.Set
		err error
	)
	switch version {
	case "1_8_9":
		set, err = gen.Data()
	case "26_1_2":
		set, err = gen26.Data()
	default:
		t.Fatalf("no data set for %q", version)
	}
	if err != nil {
		t.Fatalf("%s: load the data set: %v", version, err)
	}

	return set.Items()
}

// classifierFor asserts the optional interface rather than assuming it. New
// returns a sim.Profile, and a seam nobody asserts is the defect the master
// plan records against M7.
func classifierFor(t *testing.T, built sim.Profile) mining.Classifier {
	t.Helper()

	classifier, ok := built.(mining.Classifier)
	if !ok {
		t.Fatalf("%T does not classify mining", built)
	}

	return classifier
}

// namesFor asserts the name lookup, which is how a corpus reaches a handle.
func namesFor(t *testing.T, built sim.Profile) sim.BlockNames {
	t.Helper()

	names, ok := built.(sim.BlockNames)
	if !ok {
		t.Fatalf("%T cannot resolve a block name", built)
	}

	return names
}

// refOf resolves a block the corpus names.
//
// The corpus holds the registry name the jar used, namespace and all, because
// that is what the game called it. The generated data is keyed by the path
// alone, so the namespace comes off here rather than being left out of the
// corpus — a corpus that dropped it would be recording a name no version
// actually uses.
func refOf(t *testing.T, names sim.BlockNames, name string) world.BlockRef {
	t.Helper()

	ref, ok := names.Ref(unqualified(name))
	if !ok {
		t.Fatalf("this version has no block %q", name)
	}

	return ref
}

// itemOf resolves a tool the corpus names.
func itemOf(t *testing.T, items data.ItemRegistry, name string) data.ItemID {
	t.Helper()

	item, ok := items.ByName(unqualified(name))
	if !ok {
		t.Fatalf("this version has no item %q", name)
	}

	return item.ID
}

// unqualified drops the namespace from a registry name.
func unqualified(name string) string {
	if _, path, found := strings.Cut(name, ":"); found {
		return path
	}

	return name
}
